CREATE TABLE shelters (
      id BIGINT NOT NULL AUTO_INCREMENT,
      name VARCHAR(100) NOT NULL UNIQUE,
      phone VARCHAR(14) NOT NULL UNIQUE,
      email VARCHAR(100) NOT NULL UNIQUE,
      PRIMARY KEY(id)
);